### ISSUE TITLE
Build instructions 

### ISSUE THREAD

**Issue by rantibi** [klg71/keycloakmigration#1]
Any chance you a can provide build instruction?
I am getting errors in build.gradle.kts, some dependancies are missing.
```
keycloakmigration (master) $ ./gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/rantibi/tieup/keycloakmigration/build.gradle.kts' line: 50

* What went wrong:
null cannot be cast to non-null type kotlin.String

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

```

it seems like the problem is with the following lines:
```
maven {
        setUrl("https://artifactory.klg71.de/artifactory/libs-releases")
        credentials {
            username = project.findProperty("artifactory_user") as String
            password = project.findProperty("artifactory_password") as String
        }
    }
```

(I am new with Gradle and Kotlin)

**Comment by klg71** [comment]
Hey rantibi,

Thanks for you report :)

I will remove my private artifactory server then it should work properly.

Will make another comment when you can pull the new master.

**Comment by klg71** [comment]
Ok should be fixed please pull a new master

**Comment by rantibi** [comment]
I don't see new commit, the last one was 8 days ago

**Comment by klg71** [comment]
May you try again pls? I pushed to the wrong remote :/

**Comment by rantibi** [comment]
It works now, thank you!
I will be happy to contribute to this repo when you will add license

**Comment by rantibi** [comment]
please remove the following too:
https://github.com/klg71/keycloakmigration/blob/master/build.gradle.kts#L62-L63

**Comment by klg71** [comment]
Can't do that because then i would be unable to publish it myself
