### ISSUE TITLE
Should wait for Keycloak to be ready before executing migrations

### ISSUE THREAD

**Issue by sideisra** [klg71/keycloakmigration#11]
When using this plugin a common use case is to migrate local test installations of a keycloak, e.g. to configure a keycloak started via docker to support local executions or tests. Such migrations often happen right after the start of a local keycloak and fail because the keycloak is not ready yet.

Therefore it would be great to have an option to make the migration wait for the keycloak to become available.

**Comment by klg71** [comment]
Hey @sideisra thanks for opening this issue and providing this pull request however i would like to add another parameter defining the maximum wait time defaulting to null(=infinit waittime). I would use your pr and implement it myself if you agree 😊

**Comment by sideisra** [comment]
No problem. Good idea.

klg71 <notifications@github.com> schrieb am Mo., 22. Juni 2020, 19:37:

**Comment by klg71** [comment]
Released with version 0.1.32 Please check @sideisra :)
