### ISSUE TITLE
Add support for setting "+" to the web origins of a client

### ISSUE THREAD

**Issue by Soerinho** [klg71/keycloakmigration#13]
When using the plugin i tried to set "+" for the web origins of a client. I did a successful test with the character "*" but "+" didn't work.

It would be great if there is an option to use a "+" for the web origins.

**Comment by klg71** [comment]
Hello @Soerinho thanks for opening this issue. I already investigated the issue and prepared a fix in 0.1.33 which will be released soon 😊

**Comment by klg71** [comment]
Released with version 0.1.33 please check if it fits your needs @Soerinho  :)

**Comment by Soerinho** [comment]
Hi @klg71, yep it works. Thx for the quick fix :-)
