### ISSUE TITLE
Migrate without "list realm" permission in keycloak

### ISSUE THREAD

**Issue by Soerinho** [klg71/keycloakmigration#15]
When using the plugin i tried to start a migration without the permission to list the keycloak realms. In this case i got the following error:
`Instantiation of [simple type, class de.klg71.keycloakmigration.model.Realm] value failed for JSON property id due to missing (therefore NULL) value for creator parameter id which is a non-nullable type
   at [Source: (BufferedReader); line: 1, column: 25] (through reference chain: java.util.ArrayList[0]->de.klg71.keycloakmigration.model.Realm["id"])`

**Comment by klg71** [comment]
Hello @Soerinho  thanks for opening this issue! :) The rootCause behind this bug is, that if you dont have the permission to inpect the realm you are on, you only get a reduced realm list from the /auth/admin/realms endpoint. I should be able to prepare the fix in the version 0.1.34 today.

**Comment by klg71** [comment]
Released version 0.1.34. Please review the fix @Soerinho and reopen if needed :)

**Comment by Soerinho** [comment]
Hi @klg71 my test was successful :-) Thx for the quick fix 👍
