### ISSUE TITLE
Support for role scope mappings

### ISSUE THREAD

**Issue by sideisra** [klg71/keycloakmigration#17]
Clients can be configured to map only some roles into the token. It is called [Role Scope Mapping](https://www.keycloak.org/docs/latest/server_admin/#_role_scope_mappings) an can be found in the "Scope" tab of the admin console. We need to configure these mappings in our clients. It would be great when this migrations is supported.

**Comment by klg71** [comment]
Hey @sideisra thanks for opening this issue and preparing the pull request. I woll look into it immediately.

**Comment by klg71** [comment]
Hey @sideisra this feature is released with version: 0.1.44 :)
