### ISSUE TITLE
Docker image prints all env vars

### ISSUE THREAD

**Issue by mgerhardy** [klg71/keycloakmigration#25]
I'm using your docker image in a kubernetes environment as a job. And I've noticed that you print all env vars in either the docker container or in your application. This will put all env vars mounted from secrets into potentially public logs.

It would be cool if you could make this configurable or disable it.

**Comment by klg71** [comment]
Hello @mgerhardy thanks for opening this issue :)

I plan to deactivate the env printing completly. and add an env_parameter ("PRINT_ARGUMENTS") to optionally print the arguments supplied to the keycloakmigration.jar.

**Comment by klg71** [comment]
Released with version 0.1.61 would you please verify @mgerhardy  :)
