### ISSUE TITLE
Add support for User Federation Mappers

### ISSUE THREAD

**Issue by thomasdarimont** [klg71/keycloakmigration#6]

**Comment by klg71** [comment]
After a first look at the keycloak api I think I'm able to implement a basic version for User Federation Mappers.
This change would make it possible to create User Federation Mappers for AD LDAP User Federations.
But you will have to use the browser and the Network Analysis Tool to provide the right config for needed mappers.
Maybe you can give me some important mappers for you to begin, than I could provide a more convenient command to add an User Federation Mapper.

**Comment by thomasdarimont** [comment]
Hi @klg71 take a look at this: https://www.keycloak.org/docs/latest/server_admin/index.html#adding-mappers

**Comment by klg71** [comment]
Hi @thomasdarimont I released version 0.1.30 with the convenience actions for the mappers in the link you provided. Also there is an action to create a custom mapper with custom configurations. Can you please check if this fits your needs? :)
